config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'entries#index'
  
  resources :entries, only: [:create, :new, :destroy, :update, :edit]

  post 'shift_date_left', to: 'entries#shift_date_left'
  post 'shift_date_right', to: 'entries#shift_date_right'
  post 'submit_api_call', to: 'entries#submit_api_call'

  get 'report', to: 'reports#show'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/entry.rb
class Entry < ApplicationRecord
    belongs_to :user, foreign_key: "user_id"
    
    validate :validate_all_non_negative
    validates :sleep_hrs, numericality: { less_than_or_equal_to: 24 }

    validates :entry_date, uniqueness: { scope: :user_id, message: "should be unique per user. Please edit it instead" }

    [
        :mood,
        :steps,
        :sleep_hrs,
        :protein, 
        :carbs, 
        :fats
    ].each do |key|
        validates key, numericality: true
    end

    
    def validate_non_negative(field)
        fieldvalue = send(field)
        if fieldvalue < 0
            errors.add field, "can't be negative"
            return false
        end
        true
    end

    private 

    def validate_all_non_negative
        numerical_inputs = [
            :mood, :steps, :sleep_hrs, :protein, :carbs, :fats
        ]
        numerical_inputs.each do |field_key|
            validate_non_negative field_key
        end
        puts errors
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
    before_action :set_current_date
    before_action :initialize_session_hash


    def submit_api_call
        # user_input = params[:user_input]
        selected_entry = Entry.find_by(id: params[:entry])

        protein_ratio = ((4.0 * selected_entry.protein) / selected_entry.calories_in).round(2) * 100
        carbs_ratio = ((4.0 * selected_entry.carbs) / selected_entry.calories_in).round(2) * 100
        fats_ratio = ((9.0 * selected_entry.fats) / selected_entry.calories_in).round(2) * 100

        llm_prompt = %(
            Given the following statistics, give an overview of my lifestyle choices in under 100 words.

            Today I consumed #{selected_entry.protein} grams of protein, #{selected_entry.carbs} grams of carbs, and #{selected_entry.fats} grams of fats. 
            This was a ratio of #{protein_ratio}:#{carbs_ratio}:#{fats_ratio} as a contribution to my total calorie intake of #{selected_entry.calories_in}.

            During the day I took #{selected_entry.steps} steps, which burned #{0.05 * selected_entry.steps} calories.
            Last night I slept #{selected_entry.sleep_hrs} hours.

            Overall, I would rate my mood for today as #{selected_entry.mood} out of 10.
        )

        @response = call_openai_api(llm_prompt)

        # Store the response in the session hash with the entry ID as the key
        session[:api_responses] = {"id" => params[:entry], "response" => @response}        
        
        @current_date = params[:date]
        redirect_to root_path(date: @current_date)
    end

    def index
        if user_signed_in?
            @entry = Entry.find_by(user_id: current_user.id, entry_date: @current_date)

            if @entry.nil?
                @nutrition_data = {}
            else
                @nutrition_data = {
                        'Protein' => (4.0 * @entry.protein),
                        'Fat' => (9.0 * @entry.fats),
                        'Carbs' => (4.0 * @entry.carbs)
                }
            end
        
        else
            redirect_to user_session_path, alert: "You must be signed in to do that!"
        end
    end

    def edit
        @entry = Entry.find(params[:id])
        @current_date = params[:date]
    end

    def update
        @entry = Entry.find(params[:id])
        @current_date = params[:date]
        if @entry.update(update_entry_params)
            redirect_to root_path(date: @current_date), notice: 'Journal entry was successfully updated.'
        else
            render :edit
        end
    end

    def shift_date_left
        @current_date = @current_date - 1.day
        redirect_to root_path(date: @current_date)
    end

    def shift_date_right
        @current_date = @current_date + 1.day
        redirect_to root_path(date: @current_date)
    end
 
    def new
        if user_signed_in?
            @entry = Entry.new()
        else
            redirect_to new_user_session_path, alert: "You must be signed in to do that!"
        end
    end
 
    def create
        new_params = entry_params
        new_params["user_id"] = current_user.id
        # new_params["entry_date"] = @current_date
        @entry = Entry.new(new_params)
        @current_date = new_params['entry_date']
        if @entry.save
            redirect_to root_url(date: @current_date)
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        Entry.find(params[:id]).destroy
        redirect_to root_path
    end
 
    private

    def set_current_date
        @current_date = params[:date].present? ? Date.parse(params[:date]) : Date.today
    end
 
    def entry_params
        params.require(:entry).permit(:entry_date, :description, :mood, :sleep_hrs, :steps, :protein, :carbs, :fats)
    end

    def update_entry_params
        params.require(:entry).permit(:description, :mood, :sleep_hrs, :steps, :protein, :carbs, :fats)
    end

    def call_openai_api(prompt)
        response = HTTP.auth("Bearer #{ENV['OPENAI_API_KEY']}").post(
            "https://api.openai.com/v1/chat/completions",
            json: {
                model: 'gpt-4o',
                messages: [
                    
                    {
                        role: "system",
                        content: "You are a health, nutrition and lifestyle expert. Given some statistics about a persons lifestyle, you are to provide a brief summary of their choices, including what is good. Wherever possible, please suggest improvements that they could make."
                    },
                    {
                        role: "user",
                        content: prompt,
                    }
                ],
            }
        )
        
        content = response.parse["choices"][0]["message"]["content"]
        return content
    end

    def initialize_session_hash
        session[:api_responses] ||= {}
      end
end

app/helpers/entries_helper.rb
require 'date'

module EntriesHelper
    def entry_form(entry)
        form_with(model: entry) do |form|
            concat content_tag(:h1, "Log Your Day", class: "text-lg font-semibold mb-2", style: "text-align: center")
            concat form.label(:title, "Enter your title...")
            concat form.text_field(:title, class: "form-control border-primary mb-1", required: true, placeholder: "Enter title...")

            concat content_tag(:h2, "How are you feeling?", class: "text-lg font-semibold mb-2", style: "text-align: center")

            concat form.label(:description, "Enter your description...")
            concat form.text_field(:description, class: "form-control border-primary mb-1", required: true, placeholder: "Enter description...")
        
            concat form.label(:mood, "Rate your mood between 0 and 10")
            concat form.select(:mood, 0..10, class: "form-control border-primary mb-1")
        
            concat content_tag(:h2, "Health Tracker", class: "text-lg font-semibold mb-2", style: "text-align: center")
        
            concat form.label(:sleep_hrs, "Enter your sleep in hours...")
            concat form.number_field(:sleep_hrs, max: 24, class: "form-control border-primary mb-1")
        
            concat form.label(:steps, "Enter your daily steps...")
            concat form.number_field(:steps, class: "form-control border-primary mb-1")
        
            concat form.label(:protein, "Enter your protein in grams...")
            concat form.number_field(:protein, class: "form-control border-primary mb-1")
        
            concat form.label(:carbs, "Enter your carbs in grams...")
            concat form.number_field(:carbs, class: "form-control border-primary mb-1")
        
            concat form.label(:fats, "Enter your fat in grams...")
            concat form.number_field(:fats, class: "form-control border-primary mb-1", placeholder: "Enter your fat in grams...")
        
            concat form.submit
        end
      end

      def format_date_with_suffix(date)
        # Format the date to get day, month, and year
        formatted_date = date.strftime('%a %d %b %Y')
      
        # Extract the day part and determine the suffix
        day = date.day
        suffix = case day
                 when 1, 21, 31 then 'st'
                 when 2, 22 then 'nd'
                 when 3, 23 then 'rd'
                 else 'th'
                 end
      
        # Replace the day number with the day number + suffix
        formatted_date.sub(/\d{2}/, "#{day}#{suffix}")
      end

      def generate_pie_chart_desc(nutrition_data)
        "This Pie Chart displays your macronutrient breakdown for the day. You consumed #{nutrition_data['Protein']}, #{nutrition_data['Carbs']} and #{nutrition_data['Fat']} calories worth of proteins, carbs and fats, respectively."

      end
  end

app/views/entries/_form.html.erb
<%= form_with(model: @entry) do |form| %>
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">How are you feeling?</h3>
    <%= form.text_field :title, class: "form-control border-primary mb-1", required: true, placeholder: "Enter title..." %>
    <%= form.text_field :description, class: "form-control border-primary mb-1", required: true, placeholder: "Enter description..." %>

    <%= form.label :mood, "Rate your mood between 0 and 10"%>
    <%= form.select :mood, 0..10, class: "form-control border-primary mb-1"%>
    
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">Health Tracker</h3>

    <%= form.label :sleep_hrs, "Enter your sleep in hours..."%>
    <%= form.number_field :sleep_hrs, max: 24, class: "form-control border-primary mb-1"%>

    <%= form.label :steps, "Enter your daily steps..."%>
    <%= form.number_field :steps, class: "form-control border-primary mb-1"%>

    <%= form.label :protein, "Enter your protein in grams..."%>
    <%= form.number_field :protein, class: "form-control border-primary mb-1"%>

    <%= form.label :carbs, "Enter your carbs in grams..."%>
    <%= form.number_field :carbs, class: "form-control border-primary mb-1"%>

    <%= form.label :fats, "Enter your fat in grams..."%>
    <%= form.number_field :fats, class: "form-control border-primary mb-1", placeholder: "Enter your fat in grams..."%>

    <%= form.submit %>
<% end %>

app/views/entries/edit.html.erb
</br>
<h1 style="text-align: center">Update your entry for <%= @current_date %></h2>
<div class="card">
    <%= form_with(model: @entry, url: entry_path(@entry, date: @current_date)) do |form| %>
    <% if @entry.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
        <ul>
            <% @entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">How are you feeling?</h3>

    <%= form.label :description, "How was your day?" %>
    <%= form.text_area :description, class: "form-control border-primary mb-1", required: true, placeholder: "Enter description..." %>

    <%= form.label :mood, "Rate your mood between 0 and 10"%>
    <%= form.select :mood, 0..10, class: "form-control border-primary mb-1"%>
    
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">Health Tracker</h3>

    <%= form.label :sleep_hrs, "Enter your sleep in hours..."%>
    <%= form.number_field :sleep_hrs, max: 24, class: "form-control border-primary mb-1"%>

    <%= form.label :steps, "Enter your daily steps..."%>
    <%= form.number_field :steps, class: "form-control border-primary mb-1"%>

    <%= form.label :protein, "Enter your protein in grams..."%>
    <%= form.number_field :protein, class: "form-control border-primary mb-1"%>

    <%= form.label :carbs, "Enter your carbs in grams..."%>
    <%= form.number_field :carbs, class: "form-control border-primary mb-1"%>

    <%= form.label :fats, "Enter your fat in grams..."%>
    <%= form.number_field :fats, class: "form-control border-primary mb-1", placeholder: "Enter your fat in grams..."%>

    <%= form.submit %>
<% end %>
</div>

app/views/entries/index.html.erb
  <div class="button-group">
    <%= button_to "Previous", shift_date_left_path(date: @current_date), class: "button1" %>
    <span class="button1 date-button">
        <% if @current_date == Date.today %>
            <%= "Today" %>
        <% else %>
            <%= format_date_with_suffix(@current_date) %>
        <% end %>
    </span>
    <%= button_to "Next", shift_date_right_path(date: @current_date), class: "button3" %>
  </div>
<% if @entry.nil? %>
    <div class="alert alert-success", style="text-align: center; width: auto; margin-left: 25%; margin-right: 25%; margin-top: 20px; margin-bottom: 10px">
        <p>
            You haven't logged an entry for <%= @current_date %>.
        </p>
        <p>
            Create a new entry <%= link_to "here", new_entry_path(date: @current_date) %>
        </p>
    </div>
<% else %>
    <div class="card buttons-card">
        <%= button_to 'Delete Entry', entry_path(@entry), method: :delete, class: "button btn-25" %>
        <%= link_to "New Entry", new_entry_path(@entry, date: @current_date), class: "button btn-50" %>
        <%= link_to 'Edit Entry', edit_entry_path(@entry, date: @current_date), method: :get, class: "button btn-75" %>
    </div>
    <div class="card">
    <div class="container mt-10">
        <!-- Row 1 -->
        <div class="left">
        </div>
        <div class="middle">
            <div class="column-content figure">
                <h2 style="font-size: 30px;">Macronutrient Breakdown (<%= @entry.calories_in%> kCal)</h4>
                </br>
                <% chart_description = generate_pie_chart_desc(@nutrition_data) %>
                <div role="img" aria-label="<%= chart_description %>" id="nutrientpie-chart">
                    <%= pie_chart @nutrition_data, legend: true, height: '400px', width: '100%'%>
                </div>
            </div>
        </div>
        <div class="right">
        </div>
        <!-- Row 2 -->
        <div class="left">
            <div class="column-content">
                <h2 style="font-size: 30px;">Mood (0-10)</h2>
                <p style="font-size: 30px;"><%= @entry.mood %></p>
            </div>
        </div>
        <div class="right">
            <div class="column-content">
                <h2 style="font-size: 30px;">Calories Burned</h2>
                <p style="font-size: 30px;"><%= (0.05 * @entry.steps).round(2) %>kCal</p>
            </div>
        </div>
        <!-- Row 3 -->
        <div class="left">
            <div class="column-content header">
                <h2 style="font-size: 30px;">Sleep (Hours)</h2>
                <p style="font-size: 30px;"><%= @entry.sleep_hrs %></p>
            </div>
        </div>
        <div class="right">
            <div class="column-content header">
                <h2 style="font-size: 30px;">Steps</h2>
                <p style="font-size: 30px;"><%= @entry.steps %></p>

            </div>
        </div>
    </div>
    </br>
    </br>
    <p style="text-align: center; font-size: 20px;">
        <%= @entry.description %>
    </p>
    </div>
    <div class='card api-card'>
        <%= button_to 'Generate Summary', submit_api_call_path(entry: @entry, date: @current_date), method: :post, class: "button btn-50", style: "width:250px;"%>
        <br><br><br>
        <% if session[:api_responses]["id"] == @entry.id.to_s %>
            <% if !session[:api_responses]['response'].nil? %>
                <p style="font-size: 15px;">
                    <%= session[:api_responses]['response'] %>
                </p>
            <% end %>
        <% end %>
    </div>

<% end %>

app/views/entries/new.html.erb
</br>
<h1 style="text-align: center">Track Your Mood & Health</h2>
<div class="card">
    <%= form_with(model: @entry) do |form| %>
    <% if @entry.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>
        <ul>
            <% @entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">How are you feeling?</h3>

    <%= form.label :entry_date, "Enter the date here..."%>
    <%= form.date_field :entry_date, class: "form-control border-primary mb-1", required: true, value: @current_date %>

    <%= form.label :description, "How was your day?" %>
    <%= form.text_area :description, class: "form-control border-primary mb-1", required: true, placeholder: "Enter description..." %>

    <%= form.label :mood, "Rate your mood between 0 and 10"%>
    <%= form.select :mood, 0..10, class: "form-control border-primary mb-1"%>
    
    <h3 class="text-lg font-semibold mb-2" style="text-align: center">Health Tracker</h3>

    <%= form.label :sleep_hrs, "Enter your sleep in hours..."%>
    <%= form.number_field :sleep_hrs, max: 24, class: "form-control border-primary mb-1"%>

    <%= form.label :steps, "Enter your daily steps..."%>
    <%= form.number_field :steps, class: "form-control border-primary mb-1"%>

    <%= form.label :protein, "Enter your protein in grams..."%>
    <%= form.number_field :protein, class: "form-control border-primary mb-1"%>

    <%= form.label :carbs, "Enter your carbs in grams..."%>
    <%= form.number_field :carbs, class: "form-control border-primary mb-1"%>

    <%= form.label :fats, "Enter your fat in grams..."%>
    <%= form.number_field :fats, class: "form-control border-primary mb-1", placeholder: "Enter your fat in grams..."%>

    <div class="text-center mt-5">
        <%= form.submit class: "btn btn-outline-dark text-center"%>
    </div>
    
<% end %>
</div>