config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'entries#index'
  
  resources :entries, only: [:create, :new, :destroy, :update, :edit]

  post 'shift_date_left', to: 'entries#shift_date_left'
  post 'shift_date_right', to: 'entries#shift_date_right'
  post 'submit_api_call', to: 'entries#submit_api_call'

  get 'report', to: 'reports#show'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light border-bottom" role="navigation">
    <div class="container-fluid">
        <div class="d-flex align-items-center">
            <%= link_to root_path, class: 'navbar-logo' do %>
                <%= image_tag 'balance_book_logo.png', alt: 'Balance Book Logo', class: 'navbar-logo' %>
            <% end %>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Reports", report_path, class: "nav-link" %>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <% if user_signed_in? %>
                    <%# link_to "Change Password", edit_password_path, class: "nav-link" %>                
                    <%= link_to 'Sign out', destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
                <% else %>
                    <%# link_to "Sign Up", new_registration_path, class: "nav-link" %>
                    <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                <% end %>
            </ul>
        </div>
    </div>
    
</nav>   